version: "3.8"
services:
  php-fpm:
    build: ./php-fpm
    volumes:
      - ../../application:/var/www/html
      - ./php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - ./php-fpm/php.ini:/usr/local/etc/php/php.ini:ro
    working_dir: /var/www/html
    user: 1000:1000

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 127:0:0:1:8080:80

  mysql:
    image: mysql:8
    volumes:
      - ./mysql/conf.d/authentication-plugin.cnf:/etc/mysql/conf.d/authentication-plugin.cnf
      - ./mysql/data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=video_service
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=db_password
    ports:
    - 127.0.0.1:3306:3306
