version: "3.8"
services:
  php-fpm:
    image: php:7.1-fpm-alpine
    ports:
      - 9000:9000
    volumes:
      - ../../application:/var/www/html
      - ./php-fpm/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - ./php-fpm/php.ini:/usr/local/etc/php/php.ini:ro
    working_dir: /var/www/html
    user: 1000:1000

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 8080:80
